
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "None"
key = "Space"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 3000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.87

[window.dimensions]
columns = 150
lines = 42

[general]
live_config_reload = true
